# Generated by Django 3.0.7 on 2020-07-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200718_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='optional',
        ),
        migrations.AddField(
            model_name='project',
            name='moreinformation',
            field=models.URLField(blank=True, null=True, verbose_name='Más Información'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
